---
######################################################
#
#    mount a smb drive
#
######################################################
# README:
#   creates a mountpoint and mounts a smb drive using variables
#
# usage: define variables in var file and rename the var1... to those variables
#

#-----------------------------------------------------
#   Header & variablen
#
- name: smb-NAS | load smb variables
  tags: archivi,smb-nas
  set_fact:
    user: "{{ architect_user }}" #gets ownership and rights to files and mounts
    smb_cred_file: "{{ architect_user_dir }}/.smbcredentials"
    local_mountpoint: "{{ nas_backup_mountpoint }}"
    remote_mountpoint: "{{ nas_backup_path }}"

#-----------------------------------------------------
#   DEBUG
#
- name: smb-NAS | DEBUG show variables
  tags: archivi,smb-nas,debug
  debug:
    msg:
      - "{{ user }} - {{ architect_user_dir }}"
      - "{{ smb_cred_file }} - {{ architect_user_dir }}/.smbcredentials"
      - "{{ local_mountpoint }} - {{ nas_backup_mountpoint }}"
      - "{{ remote_mountpoint }} - {{ nas_backup_path }}"

#-----------------------------------------------------
#   pre_tasks
#
- name: smb-NAS | Install cifs-utils
  tags: archivi,smb-nas
  ansible.builtin.package:
    name: cifs-utils
    state: present
  #register: package_install_smb_nas  #alte reboot funktion ohne handler
  notify: handler | reboot

#-----------------------------------------------------
#   Main
#
- name: smb-NAS | Create smbcredentials file
  tags: archivi,smb-nas
  ansible.builtin.template:
    src: templates/smbcredentials.j2
    dest: "{{ smb_cred_file }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0600"

- name: smb-NAS | Create mount directory
  tags: archivi,smb-nas
  ansible.builtin.file:
    path: "{{ local_mountpoint }}"
    state: directory
    mode: "0755"

- name: smb-NAS | Mount SMB share
  tags: archivi,smb-nas
  ansible.builtin.mount:
    path: "{{ local_mountpoint }}"
    src: "//{{ remote_mountpoint }}"
    fstype: cifs
    opts: "credentials={{ smb_cred_file }},uid={{ user }},gid={{ user }},vers=3.0,iocharset=iso8859-1,_netdev"
    state: mounted
  become: true

#-----------------------------------------------------
#   post_tasks
#
- name: smb-NAS | Ensure NAS mount is persistent across reboots
  tags: archivi,smb-nas
  lineinfile:
    path: /etc/fstab
    line: "//{{ remote_mountpoint }} {{ local_mountpoint }} cifs credentials={{ smb_cred_file }},uid={{ user }},gid={{ user }},vers=3.0,iocharset=iso8859-1,_netdev 0 0"
    state: present
  become: yes
#-----------------------------------------------------
#   Handlers
#

#-----------------------------------------------------
#   roles
#
