---
######################################################
#
#     INSTALL PORTAINER
#
######################################################
# README:
#   ports need to be defined as variable somewhere. here its /vars/all
#   variable syntax: role-name_app_port
#

#-----------------------------------------------------
#   Header & variablen
#
- name: Portainer | load variables 
  tags: archivi,portainer
  set_fact:
    port_1: "{{ lookup('vars', ansible_role_name + '_portainer_port1') }}"
    port_2: "{{ lookup('vars', ansible_role_name + '_portainer_port2') }}"

#-----------------------------------------------------
#   DEBUG
#
- name: Portainer | DEBUG - show loaded variables
  tags: archivi,portainer,debug
  debug:
    msg: 
      - "{{ port_1 }}"
      - "{{ port_2 }}"


#-----------------------------------------------------
#   pre_tasks
#


#-----------------------------------------------------
#   Main
#
- name: Portainer | Download Portainer image
  tags: archivi,portainer
  docker_image:
    name: portainer/portainer-ce
    source: pull

- name: Portainer | Create Portainer container
  tags: archivi,portainer
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    state: started
    restart_policy: always
    ports:
      - "{{ port_1 }}:8000"
      - "{{ port_2 }}:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

- name: Portainer | Ensure portainer_data volume is created
  tags: archivi,portainer
  docker_volume:
    name: portainer_data
    state: present


#-----------------------------------------------------
#   post_tasks
#


#-----------------------------------------------------
#   Handlers
#


#-----------------------------------------------------
#   roles
#



