---
######################################################
#
#    mount a smb drive 
#
######################################################
# README:
#   creates a mountpoint and mounts a smb drive using variables
#
# usage:  define variables in var file and rename the architect_user... to those variables
#         rename tags & name

#-----------------------------------------------------
#   Header & variablen
#
- name: mnt_hetzner | load variables 
  tags: archivi,mnt_hetzner
  set_fact:
    user: "{{ architect_user }}"      #gets ownership and rights to files and mounts
    smb_cred_file: "{{ architect_user_dir }}/.cloudcredentials"
    local_mountpoint: "{{ hetzner_storagebox_mountpoint }}"
    remote_mountpoint: "{{ hetzner_storagebox_path }}"


#-----------------------------------------------------
#   DEBUG
#
- name: mnt_hetzner | DEBUG show variables
  tags: archivi,mnt_hetzner,debug
  debug:
    msg: 
      - "{{ user }} - {{ architect_user_dir }}"
      - "{{ smb_cred_file }} - {{ architect_user_dir }}/.cloudcredentials"
      - "{{ local_mountpoint }} - {{ hetzner_storagebox_mountpoint }}"
      - "{{ remote_mountpoint }} - {{ hetzner_storagebox_path }}"

#-----------------------------------------------------
#   pre_tasks
#
- name: mnt_hetzner | Install cifs-utils
  tags: archivi,mnt_hetzner
  ansible.builtin.package:
    name: cifs-utils
    state: present
#register: package_install_smb_nas  #alte reboot funktion ohne handler
  notify: handler | reboot

#-----------------------------------------------------
#   Main
#
- name: mnt_hetzner | Create cloudcredentials file
  tags: archivi,mnt_hetzner
  ansible.builtin.template:
    src: templates/cloudcredentials.j2
    dest: "{{ smb_cred_file }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0600"

- name: mnt_hetzner | Create mount directory
  tags: archivi,mnt_hetzner
  ansible.builtin.file:
    path: "{{ local_mountpoint }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'

- name: mnt_hetzner | Mount SMB share
  tags: archivi,mnt_hetzner
  ansible.builtin.mount:
    path: "{{ local_mountpoint }}"
    src: "//{{ remote_mountpoint }}"
    fstype: cifs
    opts: "credentials={{ smb_cred_file }},uid={{ user }},gid={{ user }},iocharset=utf8,_netdev,rw,file_mode=0660,dir_mode=0770"  
    opts: "credentials={{ architect_user_dir }}/.cloudcredentials,iocharset=utf8,rw,_netdev,uid={{ architect_user}},gid={{ architect_user}},file_mode=0660,dir_mode=0770"
    state: mounted
  become: true


#-----------------------------------------------------
#   post_tasks
#
- name: mnt_hetzner | Ensure NAS mount is persistent across reboots
  tags: archivi,mnt_hetzner
  lineinfile:
    path: /etc/fstab
    line: "//{{ remote_mountpoint }} {{ local_mountpoint }} cifs credentials={{ smb_cred_file }},uid={{ user }},gid={{ user }},iocharset=utf8,_netdev,rw,file_mode=0660,dir_mode=0770 0 0"
    state: present
  become: yes


#-----------------------------------------------------
#   Handlers
#


#-----------------------------------------------------
#   roles
#





