---
######################################################
#
#     Setup borg backup scripts
#
######################################################
# README:
# Downloads and sets up borg backup scripts from my Github Repo.
# 
#

#-----------------------------------------------------
#   Header & variablen
#
#- name: task_name | load variables 
#  tags: tag1,tag2
#  set_fact:
#    var_1: 
#    var_2: 
#    var_3: "{{ beispiel_variable }}"
#    var_4: 

#-----------------------------------------------------
#   DEBUG
#
#- name: task_name | DEBUG - show loaded variables
#  tags: tag1,tag2,debug
#  debug:
#    msg: 
#      - "{{ var_1 }}"
#      - "{{ var_2 }}"
#      - "{{ var_3 }}"
#      - "{{ var_4 }}"


#-----------------------------------------------------
#   pre_tasks
#


#-----------------------------------------------------
#   Main
#
- name: BORG | Ensure borg is installed
  tags: archivi,borg,borg_update
  package:
    name: 
      - "{{ borg_package }}"
    state: present
    update_cache: yes

- name: BORG | Ensure borg_script_path directory exists
  tags: archivi,borg,borg_update
  file:
    path: "{{ borg_script_path }}"
    state: directory
    mode: '0755'

- name: BORG | Clone the Borg backup scripts repository
  tags: archivi,borg,borg_update
  git:
    repo: "https://github.com/Peppeppa/borg-backupscript.git"
    dest: "{{ borg_script_path }}"
    version: main  # Specify the branch or tag if needed
    force: yes

- name: BORG | Ensure borg_restore_mount directory exists
  tags: archivi,borg,borg_update
  file:
    path: "{{ borg_restore_mount }}"
    state: directory
    mode: '0755'

- name: BORG | Ensure borg_log_directory exists
  tags: archivi,borg,borg_update
  file:
    path: "{{ borg_log_directory }}"
    state: directory
    mode: '0755'

- name: BORG | create config.env
  tags: archivi,borg,env,borg_update
  ansible.builtin.template: 
    src: templates/env.j2
    dest: "{{ borg_script_path }}/config.env"
    owner: "{{ architect_user }}"
    group: "{{ architect_user }}" 
    mode: '0600'

#-----------------------------------------------------
#   post_tasks
#


#-----------------------------------------------------
#   Handlers
#


#-----------------------------------------------------
#   roles
#


