---
######################################################
#
#     Setup borg backup scripts
#
######################################################
# README:
#
#

#-----------------------------------------------------
#   Header & variablen
#
#- name: task_name | load variables 
#  tags: tag1,tag2
#  set_fact:
#    var_1: 
#    var_2: 
#    var_3: "{{ beispiel_variable }}"
#    var_4: 

#-----------------------------------------------------
#   DEBUG
#
#- name: task_name | DEBUG - show loaded variables
#  tags: tag1,tag2,debug
#  debug:
#    msg: 
#      - "{{ var_1 }}"
#      - "{{ var_2 }}"
#      - "{{ var_3 }}"
#      - "{{ var_4 }}"


#-----------------------------------------------------
#   pre_tasks
#


#-----------------------------------------------------
#   Main
#

- name: BORG | create config.env
  template:
    src: templates/env.j2
    dest: "{{ borg-script-path }}/config.env"
  owner: {{ architect_user }}
  group: {{ architect_user }} 
  mode: '0644'


#-----------------------------------------------------
#   post_tasks
#


#-----------------------------------------------------
#   Handlers
#


#-----------------------------------------------------
#   roles
#


