- name: system setup | logging | adjust retention period
  tags: systemd,journal,journald,sysctl,system-setup,logging
  lineinfile:
    dest: "/etc/systemd/journald.conf"
    regexp: "^#MaxFileSec="
    line: "MaxFileSec=5day"
  register: journald_config

- name: system setup | logging | restart journald (config changed)
  tags: systemd,journal,journald,sysctl,system-setup,logging
  service:
    name: systemd-journald
    state: restarted
  when: journald_config.changed
