---
- name: smb-NAS | DEBUG show variables
  tags: archivi,smb-nas,debug
  debug:
    msg: "{{ architect_user_dir }} | {{ nas_backup_mountpoint }} | {{ nas_backup_mountpoint }} | {{ nas_backup_path }} | "
  
      
- name: smb-NAS | Install cifs-utils
  tags: archivi,smb-nas
  ansible.builtin.package:
    name: cifs-utils
    state: present
#register: package_install_smb_nas  #alte reboot funktion ohne handler
  notify: handler | reboot

- name: smb-NAS | Create smbcredentials file
  tags: archivi,smb-nas
  ansible.builtin.template:
    src: templates/smbcredentials.j2
    dest: "{{ architect_user_dir }}/.smbcredentials"
    owner: "{{ architect_user }}"
    group: "{{ architect_user }}"
    mode: "0600"

- name: smb-NAS | Create mount directory
  tags: archivi,smb-nas
  ansible.builtin.file:
    path: "{{ nas_backup_mountpoint }}"
    state: directory
    mode: '0755'

#- name: smb-NAS | reboot target maschine to make smb work    #alte reboot funktion
#  tags: archivi,smb-nas
#  reboot:
#    reboot_timeout: 300
#    pre_reboot_delay: 30
#  when: package_install_smb_nas.changed

- name: smb-NAS | Mount SMB share
  tags: archivi,smb-nas
  ansible.builtin.mount:
    path: "{{ nas_backup_mountpoint }}"
    src: "//{{ nas_backup_path }}"
    fstype: cifs
    opts: "credentials={{ architect_user_dir }}/.smbcredentials,uid={{ architect_user }},gid={{ architect_user }},vers=3.0,iocharset=iso8859-1,_netdev"  
    state: mounted
  become: true

- name: smb-NAS | Ensure NAS mount is persistent across reboots
  tags: archivi,smb-nas
  lineinfile:
    path: /etc/fstab
    line: "//{{ nas_backup_path }} {{ nas_backup_mountpoint }} cifs credentials={{ architect_user_dir }}/.smbcredentials,uid={{ architect_user }},gid={{ architect_user }},vers=3.0,iocharset=iso8859-1,_netdev 0 0"
    state: present
  become: yes

#- name: smb-NAS | Set permissions on /mnt/storage
#  tags: archivi,smb-nas,permission
#  ansible.builtin.file:
#    path: /mnt
#    owner: root #hera
#    group: root #hera
#    mode: "0777"
#    recurse: yes
#  become: yes
