- name: users | root | ensure account is locked
  tags: root,users
  user:
    name: root
    password_lock: yes

- name: users | root | create group
  tags: root,users
  group:
    name: ansible
    state: present
