---
- name: DOTFILES | share_user | Ensure required packages are installed
  tags: dotfiles
  ansible.builtin.package:
    name:
      - git
      - stow
    state: present

#- name: DOTFILES | share_user | Ensure git is installed
#  tags: dotfiles
  #  ansible.builtin.package:
    #  name: git
    #state: present

#- name: DOTFILES | share_user | Ensure stow is installed
  #  tags: dotfiles
  #ansible.builtin.package:
    #  name: stow
    #state: present

- name: DOTFILES | share_user | Create git directory in home folder
  tags: dotfiles
  ansible.builtin.file:
    path: "{{ share_user_dir }}/git"
    state: directory
    mode: '0755'
    owner: "{{ share_user }}"
    group: "{{ share_user }}"

- name: DOTFILES | share_user | Clone dotfiles repository
  tags: dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/Peppeppa/dotfiles-stow.git'
    dest: '{{ share_user_dir }}/git/dotfiles-stow'
    update: yes

- name: DOTFILES | share_user | Setze Besitzer und Gruppe für das geklonte Repository
  tags: dotfiles
  file:
    path: '{{ share_user_dir }}/git/dotfiles-stow'
    owner: "{{ share_user }}"
    group: "{{ share_user }}"
    state: directory

- name: DOTFILES | share_user | Setze Besitzer und Gruppe für das geklonte Repository
  tags: dotfiles,configfiles
  file:
    path: '{{ share_user_dir }}/.config'
    owner: "{{ share_user }}"
    group: "{{ share_user }}"
    state: directory


#- name: Ensure scripts directory exists in home folder
  #  tags: dotfiles
  #ansible.builtin.file:
    #  path: "{{ share_user_dir }}/scripts"
    #state: directory
    #mode: '0755'
    #owner: "{{ share_user }}"
    #group: "{{ share_user }}"


      
#- name: Copy stow.sh script to ~/scripts
  #  tags: dotfiles
  #ansible.builtin.copy:
    #  src: scripts/stow.sh
    #dest: "{{ share_user_dir }}/scripts/stow.sh"
    #mode: '0755'
    #owner: "{{ share_user }}"
    #group: "{{ share_user }}"

- name: DOTFILES | share_user | Delete existing files in the home directory
  tags: dotfiles
  file:
    path: "{{ share_user_dir }}/.bashrc"
    state: absent

#- name: Execute the stow.sh script
  #  tags: dotfiles
  #command: "{{ share_user_dir }}/scripts/stow.sh"
  #args:
    #  chdir: "{{ share_user_dir }}/scripts"
  #environment:
    #  HOME: "{{ share_user_dir }}"
- name: DOTFILES | share_user | Symlinks für Dotfiles erstellen
  tags: dotfiles
  command: "stow -d {{ share_user_dir }}/git/dotfiles-stow/ -t {{ architect_user_dir }}/ bashrc alacritty neofetch nvim tmux zsh"
  args:
    chdir: "{{ share_user_dir }}/git/dotfiles-stow"

