- name: system setup | utilities | install utility packages
  tags: software,packages,system,settings
  package:
    state: latest
    name:
      - at
      - colordiff
      - curl
      - "{{ dns_utils_package}}"
      - htop
      - iotop
      - "{{ lm_sensors_package }}"
      - lsof
      - mc
      - mosh
      - ncdu
      - neofetch
      - net-tools
      - "{{ nfs_client_package }}"
      - nmap
      - ranger
      - "{{ rename_package }}"
      - rsync
      - screen
      - sshfs
      - tmux
      - traceroute
      - "{{ vim_package }}"
      - wget
      - whois
      - zsh
      - vim
      - neovim
      - qemu-guest-agent
      - cifs-utils
  register: package_install

- name: system setup | utilities | install man-pages (arch)
  tags: software,packages,system,settings
  pacman:
    state: latest
    name:
      - man-db
      - man-pages
  when: ansible_distribution == "Archlinux"

- name: Reboot 
  tags: software,packages,system,settings
  ansible.builtin.reboot:
    msg: "Rebooting "
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
  when: package_install.changed
