---
#- name: Ensure Docker is installed
#  tags: fastdocker,portainer
#  apt:
#    name: docker.io
#    state: present
#    update_cache: yes

- name: Load docker ports variables
  tags: fastdocker,portainer
  include_vars: ../vars/docker-ports.yml

- name: Debug portainer ports
  tags: fastdocker,portainer
  debug:
    msg: "Portainer will use ports {{ portainer_1_1 }} and {{ portainer_1_2 }}"

- name: Download Portainer image
  tags: fastdocker,portainer
  docker_image:
    name: portainer/portainer-ce
    source: pull

- name: Create Portainer container
  tags: fastdocker,portainer
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    state: started
    restart_policy: always
    ports:
      - "{{ portainer_1_1 }}:8000"
      - "{{ portainer_1_2 }}:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

- name: Ensure portainer_data volume is created
  tags: fastdocker,portainer
  docker_volume:
    name: portainer_data
    state: present
