---
# tasks file for archivum-sanctum
#- name: Include vars from vars.yml
#  include_vars: "{{ role_path }}/vars/docker-ports.yml"
- name: Lade distributionsspezifische Variablen
  tags: vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
  tags: always

- block:
    #  - import_tasks: "{{ role_path }}/tasks/setup/smb-nas-downloads.yml"
    - import_tasks: "{{ role_path }}/tasks/setup/docker-ce-complete.yml"
    #  - import_tasks: "{{ role_path }}/tasks/setup/mount_smb_nas.yml"
    - import_tasks: "{{ role_path }}/tasks/setup/mount_smb_nas_borg.yml"
    - import_tasks: "{{ role_path }}/tasks/setup/portainer.yml"
  #  - import_tasks: "{{ role_path }}/tasks/setup/gocryptfs.yml"
    - import_tasks: "{{ role_path }}/tasks/setup/setup_borg_scripts.yml"

  #    Apps
#  - import_tasks: "{{ role_path }}/tasks/docker-compose/paperless.yml"
