---
- name: Lade distributionsspezifische Variablen
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
  tags: always

- block:
    - import_tasks: "{{ role_path }}/tasks/setup/mount_smb_nas_borg.yml"
    - import_tasks: "{{ role_path }}/tasks/setup/mount_smb_hetzner.yml"
    - import_tasks: "{{ role_path }}/tasks/setup/setup_borg_scripts.yml"
